from __future__ import annotations

import hashlib
import json
import time
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, cast
from uuid import UUID

import numpy as np
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from aegis_api.config import Settings
from aegis_api.models import (
    AuditEvent,
    SyntheticDatasetVersion,
    SyntheticModelCandidate,
    SyntheticRegistryModel,
    SyntheticScoringJob,
    SyntheticTrainingRun,
)
from aegis_services.features import canonical_hash
from aegis_services.ml import GATE_5SA_HASHES
from aegis_services.ml.training import CLASS_ORDER, validate_onnx_closed_policy
from aegis_services.synthetic import (
    select_model_matrix,
    synthetic_artifact_path,
    verify_synthetic_artifact,
)

MAX_ROWS = 10_000
CHUNK_ROWS = 1  # Gate 5S-B ONNX contract fixes the batch dimension to one.
LIMITATIONS = (
    "SYNTHETIC DEMO ONLY. This dataset and its labels were generated by AegisAI "
    "scenarios to test software contracts. Results do not measure UNSW-NB15 "
    "performance, real-network intrusion detection, generalization, zero-day "
    "detection, production readiness, or prevention suitability. The model is "
    "offline-only and cannot create or modify alerts or prevention actions."
)


def _safe_path(root: Path, object_ref: str, suffix: str) -> Path:
    path = (root.resolve() / f"{object_ref}.{suffix}").resolve()
    if path.parent != root.resolve():
        raise ValueError("ml_artifact_path_invalid")
    return path


def _is_accepted_synthetic_dataset(dataset: SyntheticDatasetVersion) -> bool:
    manifest = dataset.manifest
    return (
        manifest.get("dataset_kind") == "project_generated_synthetic"
        and manifest.get("synthetic_demo_only") is True
        and manifest.get("real_dataset_used") is False
        and manifest.get("unsw_nb15_acquired") is False
        and manifest.get("unsw_nb15_evaluated") is False
        and manifest.get("canonical_flow_schema") == "1"
        and manifest.get("feature_schema_name") == "flow_features"
        and manifest.get("feature_schema_version") == "1.0.0"
        and manifest.get("scenario_catalog_hash") == GATE_5SA_HASHES["scenario_catalog"]
        and manifest.get("feature_schema_hash") == GATE_5SA_HASHES["feature_schema"]
        and manifest.get("target_manifest_hash") == GATE_5SA_HASHES["target_manifest"]
        and manifest.get("split_manifest_hash") == GATE_5SA_HASHES["split_manifest"]
        and manifest.get("quality_report_hash") == GATE_5SA_HASHES["quality_report"]
        and manifest.get("leakage_report_hash") == GATE_5SA_HASHES["leakage_report"]
        and dataset.flow_sha256 == GATE_5SA_HASHES["canonical_flow_artifact"]
        and dataset.target_sha256 == GATE_5SA_HASHES["target_manifest"]
        and dataset.feature_sha256 == GATE_5SA_HASHES["feature_artifact"]
        and dataset.target_manifest_hash == GATE_5SA_HASHES["target_manifest"]
        and dataset.split_manifest_hash == GATE_5SA_HASHES["split_manifest"]
        and dataset.quality_report_hash == GATE_5SA_HASHES["quality_report"]
        and dataset.leakage_report_hash == GATE_5SA_HASHES["leakage_report"]
        and dataset.split_manifest.get("dataset_content_hash") == GATE_5SA_HASHES["dataset_content"]
    )


def score_matrix(
    payload: bytes,
    matrix: np.ndarray,
    algorithm: str,
    preprocessor: dict[str, object],
) -> dict[str, object]:
    """Run bounded, side-effect-free offline scoring over a 39-column matrix."""
    if matrix.ndim != 2 or matrix.shape[1] != 39 or matrix.shape[0] > MAX_ROWS:
        raise ValueError("ml_scoring_resource_limit")
    validate_onnx_closed_policy(payload, 39)
    values = matrix.astype(np.float32)
    if algorithm == "logistic_regression":
        values = (
            (values - np.asarray(preprocessor["center"], dtype=np.float32))
            / np.asarray(preprocessor["scale"], dtype=np.float32)
        ).astype(np.float32)
    import onnxruntime as ort

    session = ort.InferenceSession(payload, providers=["CPUExecutionProvider"])
    input_name = session.get_inputs()[0].name
    counts = {CLASS_ORDER[0]: 0, CLASS_ORDER[1]: 0}
    for offset in range(0, len(values), CHUNK_ROWS):
        labels = np.asarray(
            session.run(None, {input_name: values[offset : offset + CHUNK_ROWS]})[0]
        ).reshape(-1)
        for label in labels:
            counts[CLASS_ORDER[int(label)]] += 1
    return {"row_count": len(values), "predicted_counts": counts}


async def process_scoring_job(
    job_id: UUID, settings: Settings, factory: async_sessionmaker[AsyncSession]
) -> None:
    async with factory() as db:
        job = await db.scalar(
            select(SyntheticScoringJob).where(SyntheticScoringJob.id == job_id).with_for_update()
        )
        if job is None or job.status == "succeeded" or job.status != "pending":
            return
        registry = await db.get(SyntheticRegistryModel, job.registry_model_id)
        dataset = await db.get(SyntheticDatasetVersion, job.dataset_version_id)
        if (
            registry is None
            or registry.lifecycle_state != "reviewed_synthetic"
            or registry.expires_at <= datetime.now(UTC)
        ):
            job.status, job.error_code, job.completed_at = (
                "failed",
                "ml_registry_unavailable",
                datetime.now(UTC),
            )
            db.add(
                AuditEvent(
                    actor_user_id=job.requested_by,
                    action="synthetic.model.score.fail",
                    resource_type="synthetic_scoring_job",
                    resource_id=str(job.id),
                    outcome="failure",
                    correlation_id=f"ml-score-{job.id}",
                    safe_metadata={"error_code": job.error_code, "synthetic_demo_only": True},
                )
            )
            await db.commit()
            return
        if (
            dataset is None
            or dataset.lifecycle_state != "accepted_synthetic"
            or not _is_accepted_synthetic_dataset(dataset)
            or dataset.artifacts_deleted_at is not None
        ):
            job.status, job.error_code, job.completed_at = (
                "failed",
                "ml_dataset_not_accepted",
                datetime.now(UTC),
            )
            db.add(
                AuditEvent(
                    actor_user_id=job.requested_by,
                    action="synthetic.model.score.fail",
                    resource_type="synthetic_scoring_job",
                    resource_id=str(job.id),
                    outcome="failure",
                    correlation_id=f"ml-score-{job.id}",
                    safe_metadata={"error_code": job.error_code, "synthetic_demo_only": True},
                )
            )
            await db.commit()
            return
        job.status, job.started_at = "processing", datetime.now(UTC)
        await db.commit()
        candidate = await db.get(SyntheticModelCandidate, registry.candidate_id)
        run = await db.get(SyntheticTrainingRun, candidate.training_run_id) if candidate else None
    try:
        if candidate is None or run is None or run.dataset_version_id != dataset.id:
            raise ValueError("ml_candidate_missing")
        root = settings.artifact_root / "synthetic"
        verify_synthetic_artifact(
            root,
            dataset.feature_object_ref,
            "parquet",
            expected_sha256=dataset.feature_sha256,
            expected_size=dataset.feature_size_bytes,
            maximum_size=settings.feature_max_output_bytes,
        )
        feature_path = synthetic_artifact_path(root, dataset.feature_object_ref, "parquet")
        names = tuple(dataset.manifest["feature_names"])
        matrix_table: Any = select_model_matrix(feature_path, names)
        if matrix_table.num_rows > MAX_ROWS or matrix_table.num_columns != 39:
            raise ValueError("ml_scoring_resource_limit")
        matrix = np.column_stack(
            [np.asarray(matrix_table.column(index)) for index in range(matrix_table.num_columns)]
        ).astype(np.float32)
        metadata_path = _safe_path(
            settings.artifact_root / "models", candidate.metadata_object_ref, "candidate.json"
        )
        metadata_bytes = metadata_path.read_bytes()
        if (
            metadata_path.stat().st_size != candidate.metadata_size_bytes
            or len(metadata_bytes) > 16 * 1024 * 1024
            or hashlib.sha256(metadata_bytes).hexdigest() != candidate.metadata_sha256
        ):
            raise ValueError("ml_candidate_metadata_integrity")
        metadata = json.loads(metadata_bytes)
        if (
            metadata.get("model_object_ref") != candidate.model_object_ref
            or metadata.get("model_sha256") != candidate.model_sha256
            or metadata.get("algorithm") != candidate.algorithm
            or canonical_hash(metadata.get("preprocessor")) != candidate.preprocessor_hash
            or canonical_hash(metadata.get("evaluation")) != candidate.evaluation_hash
            or canonical_hash(metadata.get("model_card")) != candidate.model_card_hash
            or metadata.get("state") != "unreviewed_candidate"
        ):
            raise ValueError("ml_candidate_metadata_binding")
        model_path = _safe_path(
            settings.artifact_root / "models", candidate.model_object_ref, "onnx"
        )
        payload = model_path.read_bytes()
        if (
            model_path.stat().st_size != candidate.model_size_bytes
            or len(payload) > 16 * 1024 * 1024
            or hashlib.sha256(payload).hexdigest() != candidate.model_sha256
        ):
            raise ValueError("ml_candidate_model_integrity")
        pre = metadata["preprocessor"]
        started = time.perf_counter()
        scored = score_matrix(payload, matrix, candidate.algorithm, pre)
        counts = scored["predicted_counts"]
        elapsed_ms = int((time.perf_counter() - started) * 1000)
        async with factory() as db:
            locked = await db.scalar(
                select(SyntheticScoringJob)
                .where(SyntheticScoringJob.id == job_id)
                .with_for_update()
            )
            if locked is None or locked.status != "processing":
                raise ValueError("ml_scoring_state_invalid")
            aggregate_counts = cast(dict[str, object], counts)
            locked.status, locked.row_count, locked.predicted_counts, locked.completed_at = (
                "succeeded",
                len(matrix),
                {**aggregate_counts, "elapsed_ms": elapsed_ms},
                datetime.now(UTC),
            )
            db.add(
                AuditEvent(
                    actor_user_id=locked.requested_by,
                    action="synthetic.model.score.succeed",
                    resource_type="synthetic_scoring_job",
                    resource_id=str(job_id),
                    outcome="success",
                    correlation_id=f"ml-score-{job_id}",
                    safe_metadata={
                        "row_count": len(matrix),
                        "synthetic_demo_only": True,
                        "online_inference_allowed": False,
                        "alert_side_effects_allowed": False,
                        "prevention_allowed": False,
                    },
                )
            )
            await db.commit()
    except Exception as error:
        async with factory() as db:
            locked = await db.scalar(
                select(SyntheticScoringJob)
                .where(SyntheticScoringJob.id == job_id)
                .with_for_update()
            )
            if locked is not None and locked.status != "succeeded":
                locked.status, locked.error_code, locked.completed_at = (
                    "failed",
                    (str(error) if str(error).startswith("ml_") else "ml_scoring_failed")[:64],
                    datetime.now(UTC),
                )
                db.add(
                    AuditEvent(
                        actor_user_id=locked.requested_by,
                        action="synthetic.model.score.fail",
                        resource_type="synthetic_scoring_job",
                        resource_id=str(job_id),
                        outcome="failure",
                        correlation_id=f"ml-score-{job_id}",
                        safe_metadata={
                            "error_code": locked.error_code,
                            "synthetic_demo_only": True,
                        },
                    )
                )
                await db.commit()
        raise


async def cleanup_scoring_results(
    settings: Settings, factory: async_sessionmaker[AsyncSession]
) -> int:
    """Delete aggregate scoring results after their explicit 30-day retention."""
    now = datetime.now(UTC)
    async with factory() as db:
        jobs = (
            await db.scalars(
                select(SyntheticScoringJob)
                .where(SyntheticScoringJob.expires_at <= now)
                .order_by(SyntheticScoringJob.expires_at)
                .limit(100)
                .with_for_update(skip_locked=True)
            )
        ).all()
        for job in jobs:
            db.add(
                AuditEvent(
                    actor_user_id=job.requested_by,
                    action="synthetic.model.score.cleanup",
                    resource_type="synthetic_scoring_job",
                    resource_id=str(job.id),
                    outcome="success",
                    correlation_id=f"ml-score-cleanup-{job.id}",
                    safe_metadata={"retention_days": 30, "synthetic_demo_only": True},
                )
            )
            await db.delete(job)
        await db.commit()
        return len(jobs)
