from __future__ import annotations

from datetime import UTC, datetime
from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from aegis_services.features import canonical_hash

SYNTHETIC_LIMITATIONS = (
    "SYNTHETIC DEMO ONLY. This dataset and its labels were generated by AegisAI "
    "scenarios to test software contracts. Results do not measure UNSW-NB15 "
    "performance, real-network intrusion detection, generalization, zero-day "
    "detection, production readiness, or prevention suitability. The model is "
    "offline-only and cannot create or modify alerts or prevention actions."
)


class SyntheticLabel(StrEnum):
    BENIGN_LIKE = "synthetic_benign_like"
    INTRUSION_LIKE = "synthetic_intrusion_like"


class ScenarioFamily(StrEnum):
    BACKGROUND_MIXED_SERVICES = "background_mixed_services"
    BACKGROUND_SPARSE_IDLE = "background_sparse_idle"
    BACKGROUND_BURSTY = "background_bursty"
    SCAN_LIKE_FANOUT = "scan_like_fanout"
    FAILURE_LIKE_SEQUENCE = "failure_like_sequence"
    CONNECTION_RATE_LIKE = "connection_rate_like"
    AMBIGUOUS_OVERLAP = "ambiguous_overlap"
    MISSING_UNKNOWN_BOUNDARY = "missing_unknown_boundary"


class SyntheticPartition(StrEnum):
    TRAINING = "training"
    VALIDATION = "validation"
    TEST = "test"


class SyntheticScenarioCatalogV1(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    contract: Literal["synthetic-flow-scenario/v1"] = "synthetic-flow-scenario/v1"
    version: Literal["1.0.0"] = "1.0.0"
    global_seed: Literal[20260714] = 20260714
    families: tuple[ScenarioFamily, ...] = tuple(ScenarioFamily)
    labels: tuple[SyntheticLabel, ...] = tuple(SyntheticLabel)
    maximum_flows: int = Field(default=10_000, ge=1, le=10_000)
    maximum_groups: int = Field(default=120, ge=1, le=120)
    payload_allowed: Literal[False] = False
    pcap_allowed: Literal[False] = False
    network_allowed: Literal[False] = False
    real_dataset_emulation_allowed: Literal[False] = False
    alert_side_effects_allowed: Literal[False] = False
    prevention_allowed: Literal[False] = False

    @model_validator(mode="after")
    def require_closed_catalog(self) -> SyntheticScenarioCatalogV1:
        if self.families != tuple(ScenarioFamily):
            raise ValueError(
                "synthetic scenario catalog must contain the approved ordered families"
            )
        if self.labels != tuple(SyntheticLabel):
            raise ValueError("synthetic label catalog must contain the approved labels")
        return self

    @property
    def catalog_hash(self) -> str:
        return canonical_hash(self)


class SyntheticTargetV1(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    contract: Literal["synthetic-target/v1"] = "synthetic-target/v1"
    example_identity_hash: str = Field(pattern=r"^[a-f0-9]{64}$")
    label: SyntheticLabel
    scenario_family: ScenarioFamily
    group_identity_hash: str = Field(pattern=r"^[a-f0-9]{64}$")
    partition: SyntheticPartition


class SyntheticArtifactV1(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    kind: Literal["canonical_flows", "targets", "features"]
    object_ref: str = Field(pattern=r"^[a-f0-9-]{36}$")
    media_type: str = Field(min_length=1, max_length=96)
    sha256: str = Field(pattern=r"^[a-f0-9]{64}$")
    size_bytes: int = Field(ge=1, le=67_108_864)
    row_count: int = Field(ge=1, le=10_000)
    column_count: int | None = Field(default=None, ge=1, le=46)


class SyntheticQualityReportV1(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    contract: Literal["synthetic-quality-report/v1"] = "synthetic-quality-report/v1"
    total_flows: int = Field(ge=1, le=10_000)
    total_groups: int = Field(ge=1, le=120)
    label_counts: dict[str, int]
    family_counts: dict[str, int]
    partition_counts: dict[str, int]
    quality_flag_counts: dict[str, int]
    invalid_count: Literal[0] = 0
    real_dataset_rows: Literal[0] = 0
    network_requests: Literal[0] = 0

    @property
    def report_hash(self) -> str:
        return canonical_hash(self)


class SyntheticLeakageReportV1(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    contract: Literal["synthetic-leakage-report/v1"] = "synthetic-leakage-report/v1"
    banned_model_columns_found: tuple[str, ...] = ()
    cross_partition_event_duplicates: Literal[0] = 0
    cross_partition_vector_duplicates: Literal[0] = 0
    cross_partition_group_duplicates: Literal[0] = 0
    cross_partition_near_duplicates: Literal[0] = 0
    near_duplicate_method: Literal["rounded-full-vector/v1"] = "rounded-full-vector/v1"
    perfect_single_feature_separators: tuple[str, ...] = ()
    limitations: tuple[str, ...] = (SYNTHETIC_LIMITATIONS,)

    @property
    def report_hash(self) -> str:
        return canonical_hash(self)


class SyntheticSplitManifestV1(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    contract: Literal["synthetic-split-manifest/v1"] = "synthetic-split-manifest/v1"
    strategy: Literal["group_time_70_15_15"] = "group_time_70_15_15"
    dataset_content_hash: str = Field(pattern=r"^[a-f0-9]{64}$")
    train_identity_hash: str = Field(pattern=r"^[a-f0-9]{64}$")
    validation_identity_hash: str = Field(pattern=r"^[a-f0-9]{64}$")
    test_identity_hash: str = Field(pattern=r"^[a-f0-9]{64}$")
    train_count: int = Field(ge=1)
    validation_count: int = Field(ge=1)
    test_count: int = Field(ge=1)
    train_group_count: int = Field(ge=1)
    validation_group_count: int = Field(ge=1)
    test_group_count: int = Field(ge=1)
    train_time_end: datetime
    validation_time_start: datetime
    validation_time_end: datetime
    test_time_start: datetime
    cross_partition_duplicates: Literal[0] = 0
    test_sealed: Literal[True] = True
    global_seed: Literal[20260714] = 20260714

    @field_validator(
        "train_time_end", "validation_time_start", "validation_time_end", "test_time_start"
    )
    @classmethod
    def require_utc(cls, value: datetime) -> datetime:
        if value.tzinfo is None:
            raise ValueError("split boundaries must include a timezone")
        return value.astimezone(UTC)

    @model_validator(mode="after")
    def validate_boundaries_and_ratio(self) -> SyntheticSplitManifestV1:
        if not (
            self.train_time_end < self.validation_time_start
            and self.validation_time_end < self.test_time_start
        ):
            raise ValueError("synthetic split time bands must not overlap")
        total = self.train_count + self.validation_count + self.test_count
        ratios = (
            self.train_count / total,
            self.validation_count / total,
            self.test_count / total,
        )
        if any(
            abs(actual - expected) > 0.05
            for actual, expected in zip(ratios, (0.70, 0.15, 0.15), strict=True)
        ):
            raise ValueError("synthetic split is outside the approved ratio tolerance")
        if (
            len({self.train_identity_hash, self.validation_identity_hash, self.test_identity_hash})
            != 3
        ):
            raise ValueError("synthetic partitions must have distinct identity hashes")
        return self

    @property
    def manifest_hash(self) -> str:
        return canonical_hash(self)


class SyntheticDatasetManifestV1(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    contract: Literal["synthetic-dataset-manifest/v1"] = "synthetic-dataset-manifest/v1"
    dataset_kind: Literal["project_generated_synthetic"] = "project_generated_synthetic"
    name: Literal["aegis_synthetic_contract_demo"] = "aegis_synthetic_contract_demo"
    version: str = Field(pattern=r"^1\.0\.[0-9]+$")
    synthetic_demo_only: Literal[True] = True
    real_dataset_used: Literal[False] = False
    unsw_nb15_acquired: Literal[False] = False
    unsw_nb15_evaluated: Literal[False] = False
    network_traffic_generated: Literal[False] = False
    online_inference_allowed: Literal[False] = False
    alert_side_effects_allowed: Literal[False] = False
    prevention_allowed: Literal[False] = False
    generator_contract: Literal["synthetic-flow-scenario/v1"] = "synthetic-flow-scenario/v1"
    generator_version: Literal["1.0.0"] = "1.0.0"
    global_seed: Literal[20260714] = 20260714
    scenario_catalog_hash: str = Field(pattern=r"^[a-f0-9]{64}$")
    canonical_flow_schema: Literal["1"] = "1"
    feature_schema_name: Literal["flow_features"] = "flow_features"
    feature_schema_version: Literal["1.0.0"] = "1.0.0"
    feature_schema_hash: str = Field(pattern=r"^[a-f0-9]{64}$")
    feature_names: tuple[str, ...] = Field(min_length=39, max_length=39)
    source_snapshot_hash: str = Field(pattern=r"^[a-f0-9]{64}$")
    total_flows: int = Field(ge=1, le=10_000)
    total_groups: int = Field(ge=1, le=120)
    artifacts: tuple[SyntheticArtifactV1, SyntheticArtifactV1, SyntheticArtifactV1]
    target_manifest_hash: str = Field(pattern=r"^[a-f0-9]{64}$")
    split_manifest_hash: str = Field(pattern=r"^[a-f0-9]{64}$")
    quality_report_hash: str = Field(pattern=r"^[a-f0-9]{64}$")
    leakage_report_hash: str = Field(pattern=r"^[a-f0-9]{64}$")
    code_version: str = Field(min_length=1, max_length=64)
    limitations_version: Literal["synthetic-demo-limitations/v1"] = "synthetic-demo-limitations/v1"
    limitations: tuple[str, ...] = (SYNTHETIC_LIMITATIONS,)
    created_at: datetime
    retention_days: Literal[30] = 30

    @field_validator("created_at")
    @classmethod
    def normalize_created_at(cls, value: datetime) -> datetime:
        if value.tzinfo is None:
            raise ValueError("created_at must include a timezone")
        return value.astimezone(UTC)

    @model_validator(mode="after")
    def validate_artifacts(self) -> SyntheticDatasetManifestV1:
        if tuple(item.kind for item in self.artifacts) != (
            "canonical_flows",
            "targets",
            "features",
        ):
            raise ValueError("synthetic dataset requires the approved ordered artifacts")
        if self.artifacts[2].column_count != 46:
            raise ValueError("synthetic feature artifact must contain exactly 39+7 columns")
        if len(self.feature_names) != len(set(self.feature_names)):
            raise ValueError("synthetic model feature names must be unique")
        return self

    @property
    def manifest_hash(self) -> str:
        return canonical_hash(self)
