import { FormEvent, useEffect, useState } from "react";
import { apiBase, apiRequest } from "./api";

type Health = { status: string; prevention_mode: string };
type User = { id: string; email: string; roles: string[]; is_active: boolean; version: number };
type Auth = { user: User; permissions: string[]; csrf_token?: string };
type Asset = {
  id: string;
  name: string;
  network_zone: string;
  criticality: string;
  is_active: boolean;
};
type Sensor = {
  id: string;
  name: string;
  sensor_type: string;
  status: string;
  credential_version: number;
};
type IngestionJob = {
  id: string;
  source_type: string;
  status: string;
  accepted_records: number;
  rejected_records: number;
  duplicate_records: number;
  error_code: string | null;
  created_at: string;
};
type RuleVersion = {
  id: string;
  rule_key: string;
  version: number;
  name: string;
  description: string;
  category: string;
  evaluator_key: string;
  parameters: Record<string, unknown>;
  window_seconds: number;
  severity: string;
  false_positive_guidance: string;
  investigation_guidance: string;
  prevention_recommendation: string;
  lifecycle_state: string;
  is_active: boolean;
};
type Alert = {
  id: string;
  source_type: string;
  category: string;
  severity: string;
  status: string;
  grouping: Record<string, unknown>;
  occurrence_count: number;
  first_seen: string;
  last_seen: string;
};
type FeatureDefinition = { name: string; dtype: string; unit: string; missing_policy: string };
type FeatureSchema = {
  id: string;
  name: string;
  version: string;
  definition_hash: string;
  lifecycle_state: string;
  ordered_definition: { features?: FeatureDefinition[]; windows?: { seconds: number }[] };
};
type FeatureJob = {
  id: string;
  feature_schema_id: string;
  ingestion_job_id: string;
  status: string;
  input_count: number;
  output_count: number;
  error_code: string | null;
  artifact: { sha256: string; row_count: number; expires_at: string } | null;
};
type DatasetVersion = {
  id: string;
  name: string;
  version: string;
  publisher: string;
  status: string;
  citation_required: boolean;
  commercial_approval_required: boolean;
  acquisition_authorized: boolean;
};
type SyntheticGenerationJob = {
  id: string;
  feature_schema_id: string;
  status: string;
  generated_flow_count: number;
  generated_group_count: number;
  error_code: string | null;
};
type SyntheticDataset = {
  id: string;
  name: string;
  version: string;
  manifest_hash: string;
  split_manifest_hash: string;
  flow_count: number;
  group_count: number;
  feature_column_count: number;
  lifecycle_state: string;
  expires_at: string;
  synthetic_demo_only: boolean;
};
type SyntheticTrainingRun = { id: string; dataset_version_id: string; status: string; selected_algorithm: string | null; selected_candidate_hash: string | null; error_code: string | null; };
type SyntheticCandidate = { id: string; training_run_id: string; algorithm: string; lifecycle_state: string; model_sha256: string; preprocessor_hash: string; evaluation_hash: string; model_card_hash: string; selected: boolean; scoring_allowed: false; };
type AnomalyDetector = { id: string; lifecycle_state: string; status: string; algorithm: string; manifest_hash: string | null; model_sha256: string | null; threshold_hash: string | null; safe_metadata: Record<string, unknown>; error_code: string | null; };
type EnsemblePolicy = { id: string; version: string; policy_hash: string; lifecycle_state: string; limitations: string; };
type AssessmentBatch = { id: string; status: string; row_count: number; aggregate: Record<string, unknown>; limitations: string; };
type ExplanationMethod = { id: string; method: string; target_algorithm: string; top_k: number; method_hash: string; lifecycle_state: string; limitations: string; };
type ExplanationBatch = { id: string; status: string; method_hash: string; target_model_hash: string; row_count: number; aggregate: Record<string, unknown>; limitations: string; };
type IntelligenceSource = { id: string; name: string; trust_level: string; enabled: boolean; source_hash: string; lifecycle_state: string; limitations: string; };
type Indicator = { id: string; indicator_type: string; value_hash: string; indicator_hash: string; confidence: number; expires_at: string; lifecycle_state: string; };
type MatchBatch = { id: string; status: string; source_hash: string; match_count: number; aggregate: Record<string, unknown>; };
type MitreTechniqueCatalog = { id: string; catalog_version: string; catalog_hash: string; techniques: { technique_id: string; name: string; tactic: string }[]; };

const syntheticLimitation = "SYNTHETIC DEMO ONLY. This dataset and its labels were generated by AegisAI scenarios to test software contracts. Results do not measure UNSW-NB15 performance, real-network intrusion detection, generalization, zero-day detection, production readiness, or prevention suitability. The model is offline-only and cannot create or modify alerts or prevention actions.";

export function App() {
  const [health, setHealth] = useState<Health | null>(null);
  const [auth, setAuth] = useState<Auth | null>(null);
  const [csrfToken, setCsrfToken] = useState("");
  const [error, setError] = useState("");
  const [assets, setAssets] = useState<Asset[]>([]);
  const [sensors, setSensors] = useState<Sensor[]>([]);
  const [users, setUsers] = useState<User[]>([]);
  const [issuedCredential, setIssuedCredential] = useState("");
  const [ingestionJobs, setIngestionJobs] = useState<IngestionJob[]>([]);
  const [rules, setRules] = useState<RuleVersion[]>([]);
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [liveAlerts, setLiveAlerts] = useState(false);
  const [featureSchemas, setFeatureSchemas] = useState<FeatureSchema[]>([]);
  const [featureJobs, setFeatureJobs] = useState<FeatureJob[]>([]);
  const [datasets, setDatasets] = useState<DatasetVersion[]>([]);
  const [syntheticJobs, setSyntheticJobs] = useState<SyntheticGenerationJob[]>([]);
  const [syntheticDatasets, setSyntheticDatasets] = useState<SyntheticDataset[]>([]);
  const [trainingRuns, setTrainingRuns] = useState<SyntheticTrainingRun[]>([]);
  const [modelCandidates, setModelCandidates] = useState<SyntheticCandidate[]>([]);
  const [anomalyDetectors, setAnomalyDetectors] = useState<AnomalyDetector[]>([]);
  const [ensemblePolicies, setEnsemblePolicies] = useState<EnsemblePolicy[]>([]);
  const [assessmentBatches, setAssessmentBatches] = useState<AssessmentBatch[]>([]);
  const [explanationMethods, setExplanationMethods] = useState<ExplanationMethod[]>([]);
  const [explanationBatches, setExplanationBatches] = useState<ExplanationBatch[]>([]);
  const [intelSources, setIntelSources] = useState<IntelligenceSource[]>([]);
  const [indicators, setIndicators] = useState<Indicator[]>([]);
  const [matchBatches, setMatchBatches] = useState<MatchBatch[]>([]);
  const [mitreCatalogs, setMitreCatalogs] = useState<MitreTechniqueCatalog[]>([]);

  const can = (permission: string) => auth?.permissions.includes(permission) ?? false;

  useEffect(() => {
    void apiRequest<Health>("/health/live")
      .then(setHealth)
      .catch(() => setError("API health is unavailable"));
    void apiRequest<Auth>("/auth/me")
      .then(async (current) => {
        const csrf = await apiRequest<{ csrf_token: string }>("/auth/csrf");
        setAuth(current);
        setCsrfToken(csrf.csrf_token);
      })
      .catch(() => undefined);
  }, []);

  useEffect(() => {
    if (!auth) return;
    if (auth.permissions.includes("assets:read")) void apiRequest<Asset[]>("/assets").then(setAssets);
    if (auth.permissions.includes("sensors:read")) void apiRequest<Sensor[]>("/sensors").then(setSensors);
    if (auth.permissions.includes("users:read")) void apiRequest<User[]>("/users").then(setUsers);
    if (auth.permissions.includes("telemetry:read")) {
      void apiRequest<IngestionJob[]>("/ingestion/jobs").then(setIngestionJobs);
    }
    if (auth.permissions.includes("rules:read")) {
      void apiRequest<RuleVersion[]>("/rules").then(setRules);
    }
    if (auth.permissions.includes("features:read")) {
      void apiRequest<FeatureSchema[]>("/feature-schemas").then(setFeatureSchemas);
      void apiRequest<FeatureJob[]>("/feature-jobs").then(setFeatureJobs);
    }
    if (auth.permissions.includes("datasets:read")) {
      void apiRequest<DatasetVersion[]>("/datasets").then(setDatasets);
    }
    if (auth.permissions.includes("synthetic_datasets:read")) {
      void apiRequest<SyntheticGenerationJob[]>("/synthetic/generation-jobs").then(setSyntheticJobs);
      void apiRequest<SyntheticDataset[]>("/synthetic/datasets").then(setSyntheticDatasets);
    }
    if (auth.permissions.includes("models:read")) {
      void apiRequest<SyntheticTrainingRun[]>("/models/training-runs").then(setTrainingRuns);
      void apiRequest<SyntheticCandidate[]>("/models/candidates").then(setModelCandidates);
      void apiRequest<AnomalyDetector[]>("/anomaly/detectors").then(setAnomalyDetectors);
      void apiRequest<EnsemblePolicy[]>("/anomaly/policies").then(setEnsemblePolicies);
      void apiRequest<AssessmentBatch[]>("/anomaly/assessments").then(setAssessmentBatches);
    }
    if (auth.permissions.includes("explanations:read")) {
      void apiRequest<ExplanationMethod[]>("/explainability/methods").then(setExplanationMethods);
      void apiRequest<ExplanationBatch[]>("/explainability/batches").then(setExplanationBatches);
    }
    if (auth.permissions.includes("intelligence:read")) {
      void apiRequest<IntelligenceSource[]>("/intelligence/sources").then(setIntelSources);
      void apiRequest<Indicator[]>("/intelligence/indicators").then(setIndicators);
      void apiRequest<MatchBatch[]>("/intelligence/match-batches").then(setMatchBatches);
    }
    if (auth.permissions.includes("mitre:read")) {
      void apiRequest<MitreTechniqueCatalog[]>("/intelligence/mitre/techniques").then(setMitreCatalogs);
    }
    if (auth.permissions.includes("alerts:read")) {
      const refresh = () => void apiRequest<Alert[]>("/alerts").then(setAlerts);
      refresh();
      const timer = window.setInterval(refresh, 30_000);
      const socket = new WebSocket(`${apiBase.replace(/^http/, "ws")}/ws/v1/alerts`);
      socket.onopen = () => setLiveAlerts(true);
      socket.onmessage = (event) => {
        const message = JSON.parse(String(event.data)) as { event?: string };
        if (message.event === "alert_changed") refresh();
      };
      socket.onerror = () => setLiveAlerts(false);
      socket.onclose = () => setLiveAlerts(false);
      return () => {
        window.clearInterval(timer);
        socket.close();
      };
    }
  }, [auth]);

  async function login(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setError("");
    const data = new FormData(event.currentTarget);
    try {
      const result = await apiRequest<Auth>("/auth/login", {
        method: "POST",
        body: JSON.stringify({ email: data.get("email"), password: data.get("password") }),
      });
      setAuth(result);
      setCsrfToken(result.csrf_token ?? "");
      event.currentTarget.reset();
    } catch (requestError) {
      setError(requestError instanceof Error ? requestError.message : "Login failed");
    }
  }

  async function logout() {
    await apiRequest<void>("/auth/logout", { method: "POST", csrfToken });
    setAuth(null);
    setCsrfToken("");
    setAssets([]);
    setSensors([]);
    setUsers([]);
    setIssuedCredential("");
    setIngestionJobs([]);
    setRules([]);
    setAlerts([]);
    setLiveAlerts(false);
    setFeatureSchemas([]);
    setFeatureJobs([]);
    setDatasets([]);
    setSyntheticJobs([]);
    setSyntheticDatasets([]);
    setTrainingRuns([]);
    setModelCandidates([]);
    setAnomalyDetectors([]);
    setEnsemblePolicies([]);
    setAssessmentBatches([]);
  }

  async function createAsset(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = event.currentTarget;
    const data = new FormData(form);
    const asset = await apiRequest<Asset>("/assets", {
      method: "POST",
      csrfToken,
      body: JSON.stringify({
        name: data.get("name"),
        network_zone: data.get("network_zone"),
        criticality: data.get("criticality"),
        is_internal: true,
      }),
    });
    setAssets((current) => [...current, asset]);
    form.reset();
  }

  async function createSensor(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = event.currentTarget;
    const data = new FormData(form);
    const result = await apiRequest<{ sensor: Sensor; credential: string }>("/sensors", {
      method: "POST",
      csrfToken,
      body: JSON.stringify({ name: data.get("name"), sensor_type: data.get("sensor_type") }),
    });
    setSensors((current) => [...current, result.sensor]);
    setIssuedCredential(result.credential);
    form.reset();
  }

  async function createUser(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = event.currentTarget;
    const data = new FormData(form);
    const user = await apiRequest<User>("/users", {
      method: "POST",
      csrfToken,
      body: JSON.stringify({
        email: data.get("email"),
        password: data.get("password"),
        roles: [data.get("role")],
      }),
    });
    setUsers((current) => [...current, user]);
    form.reset();
  }

  async function submitTelemetry(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setError("");
    const form = event.currentTarget;
    const data = new FormData(form);
    try {
      const job = await apiRequest<IngestionJob>("/ingestion/jobs", {
        method: "POST",
        csrfToken,
        body: data,
      });
      setIngestionJobs((current) => [job, ...current]);
      form.reset();
    } catch (requestError) {
      setError(requestError instanceof Error ? requestError.message : "Upload failed");
    }
  }

  async function createRuleDraft(event: FormEvent<HTMLFormElement>, current: RuleVersion) {
    event.preventDefault();
    const form = event.currentTarget;
    const data = new FormData(form);
    const threshold = Number(data.get("threshold"));
    const draft = await apiRequest<RuleVersion>(`/rules/${current.rule_key}/versions`, {
      method: "POST",
      csrfToken,
      body: JSON.stringify({
        name: current.name,
        description: current.description,
        category: current.category,
        evaluator_key: current.evaluator_key,
        parameters: { ...current.parameters, threshold },
        window_seconds: current.window_seconds,
        severity: current.severity,
        mitre_mappings: [],
        false_positive_guidance: current.false_positive_guidance,
        investigation_guidance: current.investigation_guidance,
        prevention_recommendation: current.prevention_recommendation,
        change_rationale: "Administrator-created threshold draft for reviewed regression testing.",
      }),
    });
    setRules((items) => [draft, ...items]);
    form.reset();
  }

  async function reviewRule(rule: RuleVersion) {
    const reviewed = await apiRequest<RuleVersion>(`/rule-versions/${rule.id}/review`, {
      method: "POST",
      csrfToken,
      body: JSON.stringify({
        approved: true,
        reason: "Administrator confirms deterministic regression evidence was reviewed.",
        regression_evidence: "local-sprint3-regression-suite",
      }),
    });
    setRules((items) => items.map((item) => item.id === reviewed.id ? reviewed : item));
  }

  async function activateRule(rule: RuleVersion) {
    const current = rules.find((item) => item.rule_key === rule.rule_key && item.is_active);
    const activated = await apiRequest<RuleVersion>(`/rule-versions/${rule.id}/activate`, {
      method: "POST",
      csrfToken,
      body: JSON.stringify({
        reason: "Activate the approved deterministic rule version.",
        regression_evidence: "local-sprint3-regression-suite",
        expected_active_version_id: current?.id ?? null,
      }),
    });
    setRules((items) => items.map((item) => item.rule_key === activated.rule_key
      ? { ...item, is_active: item.id === activated.id }
      : item));
  }

  async function materializeFeatures(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = event.currentTarget;
    const data = new FormData(form);
    const job = await apiRequest<FeatureJob>("/feature-jobs", {
      method: "POST",
      csrfToken,
      headers: { "Idempotency-Key": crypto.randomUUID() },
      body: JSON.stringify({
        feature_schema_id: data.get("feature_schema_id"),
        ingestion_job_id: data.get("ingestion_job_id"),
        requested_limit: 10000,
      }),
    });
    setFeatureJobs((current) => [job, ...current]);
    form.reset();
  }

  async function generateSyntheticDataset() {
    const schema = featureSchemas.find((item) => item.lifecycle_state === "approved");
    if (!schema) return;
    const job = await apiRequest<SyntheticGenerationJob>("/synthetic/generation-jobs", {
      method: "POST",
      csrfToken,
      headers: { "Idempotency-Key": crypto.randomUUID() },
      body: JSON.stringify({ feature_schema_id: schema.id }),
    });
    setSyntheticJobs((current) => [job, ...current]);
  }

  async function reviewSyntheticDataset(dataset: SyntheticDataset) {
    const reviewed = await apiRequest<SyntheticDataset>(`/synthetic/datasets/${dataset.id}/review`, {
      method: "POST",
      csrfToken,
      body: JSON.stringify({
        accepted: true,
        reason: "Gate 5S-A deterministic, leakage, integrity, and limitations evidence reviewed.",
        evidence_reference: "GATE-5SA-OWNER-REVIEW",
      }),
    });
    setSyntheticDatasets((items) => items.map((item) => item.id === reviewed.id ? reviewed : item));
  }

  async function trainSyntheticCandidates(dataset: SyntheticDataset) {
    const run = await apiRequest<SyntheticTrainingRun>("/models/training-runs", {
      method: "POST", csrfToken, headers: { "Idempotency-Key": crypto.randomUUID() },
      body: JSON.stringify({ dataset_version_id: dataset.id }),
    });
    setTrainingRuns((items) => [run, ...items]);
  }

  return (
    <main>
      <header>
        <div>
          <p className="eyebrow">Sprint 5 Gate 5S-C synthetic offline scoring</p>
          <h1>AegisAI NIDPS</h1>
        </div>
        <div className="status" role="status" aria-live="polite">
          {health ? `API: ${health.status} · Prevention: ${health.prevention_mode}` : "Checking API…"}
        </div>
      </header>

      {!auth ? (
        <section className="panel login" aria-labelledby="login-title">
          <h2 id="login-title">Sign in</h2>
          <p>Use an administrator-created account. Credentials are never stored in browser storage.</p>
          <form onSubmit={(event) => void login(event)}>
            <label>Email<input name="email" type="email" autoComplete="username" required /></label>
            <label>Password<input name="password" type="password" autoComplete="current-password" required /></label>
            <button type="submit">Sign in</button>
          </form>
          {error && <p className="error" role="alert">{error}</p>}
        </section>
      ) : (
        <>
          <section className="panel identity" aria-labelledby="identity-title">
            <div>
              <h2 id="identity-title">{auth.user.email}</h2>
              <p>{auth.user.roles.join(" · ")}</p>
            </div>
            <button className="secondary" onClick={() => void logout()}>Sign out</button>
          </section>
          {error && <p className="error" role="alert">{error}</p>}

          <div className="grid">
            {can("features:read") && (
              <section className="panel">
                <h2>Feature engineering</h2>
                <p>Metadata-only view. Raw endpoints, vectors, paths, labels, and dataset rows are never displayed.</p>
                {featureSchemas.map((schema) => (
                  <details key={schema.id}>
                    <summary>{schema.name} v{schema.version} · {schema.lifecycle_state}</summary>
                    <p>Windows: {(schema.ordered_definition.windows ?? []).map((window) => `${window.seconds}s`).join(", ")}</p>
                    <ul>
                      {(schema.ordered_definition.features ?? []).map((feature) => (
                        <li key={feature.name}>{feature.name} · {feature.dtype} · {feature.unit} · {feature.missing_policy}</li>
                      ))}
                    </ul>
                  </details>
                ))}
                <ul>
                  {featureJobs.map((job) => (
                    <li key={job.id}>
                      {job.status} · rows {job.output_count}
                      {job.artifact ? ` · SHA-256 ${job.artifact.sha256.slice(0, 12)}… · expires ${new Date(job.artifact.expires_at).toLocaleDateString()}` : ""}
                      {job.error_code ? ` · ${job.error_code}` : ""}
                    </li>
                  ))}
                </ul>
                {can("features:materialize") && featureSchemas.length > 0 && ingestionJobs.some((job) => job.status === "succeeded") && (
                  <form onSubmit={(event) => void materializeFeatures(event)}>
                    <label>Approved feature schema<select name="feature_schema_id" required>{featureSchemas.filter((schema) => schema.lifecycle_state === "approved").map((schema) => <option key={schema.id} value={schema.id}>{schema.name} v{schema.version}</option>)}</select></label>
                    <label>Completed ingestion job<select name="ingestion_job_id" required>{ingestionJobs.filter((job) => job.status === "succeeded").map((job) => <option key={job.id} value={job.id}>{job.source_type} · {job.id.slice(0, 8)}</option>)}</select></label>
                    <button type="submit">Materialize bounded features</button>
                  </form>
                )}
              </section>
            )}

            {can("datasets:read") && (
              <section className="panel">
                <h2>Dataset governance</h2>
                <p>Investigation metadata only. Sprint 4 has no dataset download, preview, export, or model controls.</p>
                <ul>{datasets.map((dataset) => <li key={dataset.id}>{dataset.name} · {dataset.version} · {dataset.status} · acquisition {dataset.acquisition_authorized ? "authorized" : "not authorized"}</li>)}</ul>
              </section>
            )}

            {can("synthetic_datasets:read") && (
              <section className="panel" aria-labelledby="synthetic-title">
                <h2 id="synthetic-title">Synthetic dataset gate</h2>
                <p role="note"><strong>{syntheticLimitation}</strong></p>
                <p>Fixed seed 20260714 · canonical flow v1 · 39 model features plus 7 non-model provenance columns.</p>
                <ul>
                  {syntheticJobs.map((job) => (
                    <li key={job.id}>{job.status} · flows {job.generated_flow_count} · groups {job.generated_group_count}{job.error_code ? ` · ${job.error_code}` : ""}</li>
                  ))}
                </ul>
                <ul>
                  {syntheticDatasets.map((dataset) => (
                    <li key={dataset.id}>
                      {dataset.name} v{dataset.version} · {dataset.lifecycle_state} · {dataset.flow_count} flows · {dataset.group_count} groups · {dataset.feature_column_count} columns · manifest {dataset.manifest_hash.slice(0, 12)}… · split {dataset.split_manifest_hash.slice(0, 12)}… · expires {new Date(dataset.expires_at).toLocaleDateString()}
                      {can("synthetic_datasets:review") && dataset.lifecycle_state === "generated" && (
                        <button className="secondary" onClick={() => void reviewSyntheticDataset(dataset)}>Accept exact synthetic evidence</button>
                      )}
                      {can("models:train_synthetic") && dataset.lifecycle_state === "accepted_synthetic" && (
                        <button className="secondary" onClick={() => void trainSyntheticCandidates(dataset)}>Train bounded offline candidates</button>
                      )}
                    </li>
                  ))}
                </ul>
                {can("synthetic_datasets:generate") && featureSchemas.some((schema) => schema.lifecycle_state === "approved") && (
                  <button type="button" onClick={() => void generateSyntheticDataset()}>Generate bounded synthetic evidence</button>
                )}
              </section>
            )}

            {can("models:read") && (
              <section className="panel" aria-labelledby="model-candidates-title">
                <h2 id="model-candidates-title">Unreviewed synthetic model candidates</h2>
                <p role="note"><strong>{syntheticLimitation}</strong></p>
                <p>No candidate is active, registered for scoring, loaded by the API, or allowed to affect alerts or prevention.</p>
                <ul>{trainingRuns.map((run) => <li key={run.id}>Run {run.id.slice(0, 8)} · {run.status} · selected {run.selected_algorithm ?? "not selected"}{run.error_code ? ` · ${run.error_code}` : ""}</li>)}</ul>
                <ul>{modelCandidates.map((candidate) => <li key={candidate.id}>{candidate.algorithm} · {candidate.lifecycle_state} · selected {candidate.selected ? "yes" : "no"} · model {candidate.model_sha256.slice(0, 12)}… · scoring disabled</li>)}</ul>
              </section>
            )}

            {can("models:read") && (
              <section className="panel" aria-labelledby="anomaly-title">
                <h2 id="anomaly-title">Sprint 6 offline anomaly and fusion evidence</h2>
                <p role="note"><strong>{syntheticLimitation}</strong></p>
                <p>Isolation Forest candidates remain unreviewed and offline-only. No activation, online inference, alert mutation, or prevention is available.</p>
                <ul>
                  {anomalyDetectors.map((detector) => (
                    <li key={detector.id}>{detector.algorithm} · {detector.status} · {detector.lifecycle_state} · manifest {detector.manifest_hash?.slice(0, 12) ?? "pending"}…</li>
                  ))}
                </ul>
                <ul>
                  {ensemblePolicies.map((policy) => <li key={policy.id}>Fusion policy v{policy.version} · {policy.lifecycle_state} · {policy.policy_hash.slice(0, 12)}…</li>)}
                </ul>
                <ul>
                  {assessmentBatches.map((batch) => <li key={batch.id}>Offline batch {batch.status} · rows {batch.row_count} · aggregate-only</li>)}
                </ul>
              </section>
            )}

            {can("alerts:read") && (
              <section className="panel">
                <h2>Deterministic alerts</h2>
                <p role="status">Live updates: {liveAlerts ? "connected" : "polling fallback"}</p>
                <ul>
                  {alerts.map((alert) => (
                    <li key={alert.id}>
                      {alert.severity} · {alert.category} · {alert.source_type} · occurrences {alert.occurrence_count}
                    </li>
                  ))}
                </ul>
              </section>
            )}

            {can("explanations:read") && (
              <section className="panel" aria-labelledby="explanations-title">
                <h2 id="explanations-title">Offline explainability</h2>
                <ul>
                  {explanationMethods.map((method) => (
                    <li key={method.id}>
                      {method.method} · {method.target_algorithm} · top-{method.top_k} · {method.lifecycle_state}
                    </li>
                  ))}
                </ul>
                <p role="status">Batches: {explanationBatches.length}</p>
              </section>
            )}

            {can("intelligence:read") && (
              <section className="panel" aria-labelledby="intelligence-title">
                <h2 id="intelligence-title">Threat intelligence (synthetic)</h2>
                <ul>
                  {intelSources.map((source) => (
                    <li key={source.id}>
                      {source.name} · trust {source.trust_level} · {source.lifecycle_state}
                    </li>
                  ))}
                </ul>
                <p role="status">Indicators: {indicators.length} · Match batches: {matchBatches.length}</p>
                {can("mitre:read") && (
                  <ul>
                    {mitreCatalogs.map((catalog) => (
                      <li key={catalog.id}>MITRE catalog {catalog.catalog_version} · techniques {catalog.techniques.length}</li>
                    ))}
                  </ul>
                )}
              </section>
            )}

            {can("rules:read") && (
              <section className="panel">
                <h2>Detection rules</h2>
                <p>Thresholds and evidence are versioned. Rules never invoke prevention.</p>
                <ul>
                  {rules.map((rule) => (
                    <li key={rule.id}>
                      <strong>{rule.name}</strong> v{rule.version} · {rule.lifecycle_state}
                      {rule.is_active ? " · active" : ""}
                      <p>{rule.false_positive_guidance}</p>
                      {can("rules:review") && rule.lifecycle_state === "draft" && (
                        <button className="secondary" onClick={() => void reviewRule(rule)}>Approve reviewed draft</button>
                      )}
                      {can("rules:activate") && rule.lifecycle_state === "approved" && !rule.is_active && (
                        <button className="secondary" onClick={() => void activateRule(rule)}>Activate version</button>
                      )}
                      {can("rules:write") && rule.is_active && (
                        <form onSubmit={(event) => void createRuleDraft(event, rule)}>
                          <label>New threshold<input name="threshold" type="number" min="2" max="100000" required /></label>
                          <button type="submit">Create draft version</button>
                        </form>
                      )}
                    </li>
                  ))}
                </ul>
              </section>
            )}

            {can("telemetry:read") && (
              <section className="panel">
                <h2>Telemetry ingestion</h2>
                <p>Only controlled metadata files are accepted. Uploaded content is treated as hostile.</p>
                <ul>
                  {ingestionJobs.map((job) => (
                    <li key={job.id}>
                      {job.source_type} · {job.status} · accepted {job.accepted_records} · rejected {job.rejected_records} · duplicate {job.duplicate_records}
                      {job.error_code ? ` · ${job.error_code}` : ""}
                    </li>
                  ))}
                </ul>
                {can("ingestion:submit") && (
                  <form encType="multipart/form-data" onSubmit={(event) => void submitTelemetry(event)}>
                    <label>Source type<select name="source_type" defaultValue="normalized"><option value="normalized">Canonical flow JSONL</option><option value="zeek">Zeek conn.log</option><option value="suricata">Suricata EVE JSON</option><option value="pcap">Offline PCAP</option></select></label>
                    <label>Controlled telemetry file<input name="file" type="file" required /></label>
                    <button type="submit">Submit telemetry</button>
                  </form>
                )}
              </section>
            )}

            {can("assets:read") && (
              <section className="panel">
                <h2>Assets</h2>
                <ul>{assets.map((asset) => <li key={asset.id}>{asset.name} · {asset.criticality} · {asset.network_zone}</li>)}</ul>
                {can("assets:manage") && <form onSubmit={(event) => void createAsset(event)}>
                  <label>Name<input name="name" required maxLength={128} /></label>
                  <label>Network zone<input name="network_zone" required pattern="[A-Za-z0-9_.-]+" /></label>
                  <label>Criticality<select name="criticality" defaultValue="medium"><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label>
                  <button type="submit">Register asset</button>
                </form>}
              </section>
            )}

            {can("sensors:read") && (
              <section className="panel">
                <h2>Sensors</h2>
                <ul>{sensors.map((sensor) => <li key={sensor.id}>{sensor.name} · {sensor.sensor_type} · {sensor.status}</li>)}</ul>
                {issuedCredential && <div className="credential" role="alert"><strong>Copy this credential now.</strong><code>{issuedCredential}</code><button className="secondary" onClick={() => setIssuedCredential("")}>Clear</button></div>}
                {can("sensors:manage") && <form onSubmit={(event) => void createSensor(event)}>
                  <label>Name<input name="name" required maxLength={128} /></label>
                  <label>Type<select name="sensor_type" defaultValue="flow"><option>flow</option><option>zeek</option><option>suricata</option></select></label>
                  <button type="submit">Register sensor</button>
                </form>}
              </section>
            )}

            {can("users:read") && (
              <section className="panel">
                <h2>Users</h2>
                <ul>{users.map((user) => <li key={user.id}>{user.email} · {user.roles.join(", ")}</li>)}</ul>
                {can("users:manage") && <form onSubmit={(event) => void createUser(event)}>
                  <label>Email<input name="email" type="email" required /></label>
                  <label>Temporary password<input name="password" type="password" minLength={12} maxLength={128} required /></label>
                  <label>Role<select name="role" defaultValue="Viewer"><option>Viewer</option><option>SOC Analyst</option><option>Senior Analyst</option><option>Security Administrator</option><option>System Administrator</option><option>Auditor</option></select></label>
                  <button type="submit">Create user</button>
                </form>}
              </section>
            )}
          </div>
        </>
      )}
    </main>
  );
}
