#!/usr/bin/env python3
"""Create deterministic, aggregate-only Gate P5 portfolio evidence.

This command is intentionally offline and metadata-only. It reads a fixed
allowlist of project documentation and contract constants, never invokes a
subprocess, opens a socket, reads an artifact payload, loads a model, or
accesses a dataset. The output is suitable for review, not public publication.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Final

CONTRACT: Final = "portfolio_evidence/1.0.0"
BASELINE: Final = "2e4e3a6d9c927b731237de20847214e75f6a31e8"
HOSTED_CI_RUN: Final = "29675999780"
MAX_FILE_BYTES: Final = 2 * 1024 * 1024

ACCEPTED_SYNTHETIC_HASHES: Final[dict[str, str]] = {
    "scenario_catalog": "72ba9c2ac4a993dd7c2b1b3b3e0883a342197cc01f7271d4ef8660a5ae2f5d87",
    "feature_schema": "17d374837008e6153c76c946ad3ac58abb5f516fb0e0e3f23305025fa8bfe114",
    "dataset_content": "b6bf175b3db704d65efb2fd16e83cca8a6624b4fa23ef753324bceb4aeb84b9a",
    "canonical_flow_artifact": "96d1f872a389c62e0340f6f38be8158c0ae50af51a425d278bb3ad04514c95ac",
    "target_artifact": "90494acd14c28692e6cc7aafdb126a3dd1148e080e77592ddc51c4aa7ae32f70",
    "feature_artifact": "454a6edc1d4d247f86a1e453cbec6e70ce28b9dd3bca6fe957d54782a101dfb9",
    "split_manifest": "d85192d2f35db492b5833bab06ca36ff41ac0437faff3ba76262951cb653b895",
    "quality_report": "c9705bb627da7f69eaf4d7d0da94a83b421b3d87422d96622c25c21adb60d7f4",
    "leakage_report": "2ab7379825099cbfbda2679120aa6c789f549827cf5ee45eb7fe76f80f7ec13d",
    "training_identity": "25484ad54cfbcd91dfb1312fb2faab07569baf84558acbaacce3484d7ebadea7",
    "validation_identity": "96116e2b745321f11c0e3d8e753c9b9b0f75a6d5abce2e733f0576f4ff1a770f",
    "sealed_test_identity": "ee45a32898ba678aa51b79b054d5589edb47df4b178a8b55d1fc0c6b21160eb4",
}

FALSE_CAPABILITY_FLAGS: Final[dict[str, bool]] = {
    "real_dataset_used": False,
    "unsw_nb15_acquired": False,
    "live_capture_enabled": False,
    "online_inference_allowed": False,
    "model_activation_allowed": False,
    "alert_side_effects_allowed": False,
    "prevention_allowed": False,
}

SYNTHETIC_LIMITATIONS: Final = (
    "SYNTHETIC DEMO ONLY. This dataset and its labels were generated by AegisAI "
    "scenarios to test software contracts. Results do not measure UNSW-NB15 "
    "performance, real-network intrusion detection, generalization, zero-day "
    "detection, production readiness, or prevention suitability. The model is "
    "offline-only and cannot create or modify alerts or prevention actions."
)
MONITORING_LIMITATIONS: Final = (
    "SYNTHETIC DEMO ONLY. Monitoring evidence is derived from project-generated synthetic "
    "metadata and offline artifacts. It does not measure real-network drift, UNSW-NB15 "
    "performance, production readiness, or prevention suitability. Monitoring cannot activate "
    "models or create or modify alerts, detections, incidents, or prevention actions."
)

CONTROL_FILES: Final[tuple[str, ...]] = (
    "docs/POST_MVP_GATE_P5_PLAN.md",
    "docs/POST_MVP_SYNTHETIC_ROADMAP.md",
    "docs/POST_MVP_GATE_P4_COMPLETION_REPORT.md",
    "docs/POST_MVP_GATE_P4_REPRODUCIBILITY_RUNBOOK.md",
    "README.md",
    "SECURITY.md",
    "docs/PRD.md",
    "docs/SCHEMAS.md",
    "docs/architecture/ARCHITECTURE.md",
    "docs/threat-model/THREAT_MODEL.md",
    "services/aegis_services/synthetic/schema.py",
    "services/aegis_services/monitoring/schema.py",
    "docs/portfolio/README_PORTFOLIO.md",
    "docs/portfolio/DEMO_RUNBOOK.md",
    "docs/portfolio/ARCHITECTURE_OVERVIEW.md",
    "docs/portfolio/THREAT_MODEL_SUMMARY.md",
    "docs/portfolio/SPRINT_HISTORY.md",
    "docs/portfolio/CLAIMS_REVIEW.md",
    "docs/portfolio/DEMO_TRANSCRIPT.md",
    "docs/portfolio/cards/SYNTHETIC_DATASET_CARD.md",
    "docs/portfolio/cards/FEATURE_SCHEMA_CARD.md",
    "docs/portfolio/cards/MODEL_ANOMALY_CARD.md",
    "docs/portfolio/cards/MONITORING_CARD.md",
    "docs/portfolio/cards/PREVENTION_SIMULATION_CARD.md",
    "docs/portfolio/cards/SECURITY_QA_CARD.md",
)
EVIDENCE_FILES: Final[tuple[str, ...]] = (
    "docs/SPRINT_5_GATE_5SA_COMPLETION_REPORT.md",
    "docs/SPRINT_5_GATE_5SB_COMPLETION_REPORT.md",
    "docs/SPRINT_5_GATE_5SC_COMPLETION_REPORT.md",
    "docs/POST_MVP_GATE_P1_COMPLETION_REPORT.md",
    "docs/POST_MVP_GATE_P2_COMPLETION_REPORT.md",
    "docs/POST_MVP_GATE_P3_COMPLETION_REPORT.md",
    "docs/POST_MVP_GATE_P4_COMPLETION_REPORT.md",
)


class PortfolioEvidenceError(ValueError):
    """Raised when the closed portfolio-evidence contract cannot be built."""


def _canonical_hash(value: object) -> str:
    encoded = json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode()
    return hashlib.sha256(encoded).hexdigest()


def _safe_file(root: Path, relative: str) -> Path:
    root = root.resolve()
    candidate = (root / relative).resolve()
    if candidate != root and root not in candidate.parents:
        raise PortfolioEvidenceError("control_file_outside_project")
    if not candidate.is_file():
        raise PortfolioEvidenceError(f"missing_control_file:{relative}")
    if candidate.stat().st_size > MAX_FILE_BYTES:
        raise PortfolioEvidenceError(f"control_file_too_large:{relative}")
    return candidate


def _hash_file(root: Path, relative: str) -> str:
    digest = hashlib.sha256()
    with _safe_file(root, relative).open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _read_text(root: Path, relative: str) -> str:
    return _safe_file(root, relative).read_text(encoding="utf-8")


def build_evidence(root: Path) -> dict[str, object]:
    """Build a stable portfolio evidence record without reading data payloads."""

    root = root.resolve()
    control_hashes = {relative: _hash_file(root, relative) for relative in CONTROL_FILES}
    evidence_hashes = {relative: _hash_file(root, relative) for relative in EVIDENCE_FILES}
    synthetic_source = _read_text(root, "services/aegis_services/synthetic/schema.py")
    monitoring_source = _read_text(root, "services/aegis_services/monitoring/schema.py")
    if not all(
        fragment in synthetic_source
        for fragment in (
            "SYNTHETIC DEMO ONLY.",
            "Results do not measure UNSW-NB15",
            "offline-only and cannot create or modify alerts or prevention actions.",
        )
    ):
        raise PortfolioEvidenceError("synthetic_limitation_constant_mismatch")
    if not all(
        fragment in monitoring_source
        for fragment in (
            "SYNTHETIC DEMO ONLY.",
            "does not measure real-network drift, UNSW-NB15",
            "Monitoring cannot activate ",
            "models or create or modify alerts, detections, incidents, or prevention actions.",
        )
    ):
        raise PortfolioEvidenceError("monitoring_limitation_constant_mismatch")

    stable = {
        "contract": CONTRACT,
        "baseline": BASELINE,
        "hosted_ci_run": HOSTED_CI_RUN,
        "control_file_sha256": control_hashes,
        "evidence_file_sha256": evidence_hashes,
        "accepted_synthetic_hashes": ACCEPTED_SYNTHETIC_HASHES,
        "false_capability_flags": FALSE_CAPABILITY_FLAGS,
        "limitation_text_sha256": {
            "synthetic": hashlib.sha256(SYNTHETIC_LIMITATIONS.encode()).hexdigest(),
            "monitoring": hashlib.sha256(MONITORING_LIMITATIONS.encode()).hexdigest(),
        },
        "media": {"screenshots_authorized": False, "recording_authorized": False},
        "prevention_mode": "simulation",
        "external_services_required": False,
        "raw_payloads_included": False,
        "credentials_included": False,
        "sealed_test_reopened": False,
    }
    return {
        "contract": CONTRACT,
        "identity": stable,
        "identity_sha256": _canonical_hash(stable),
        "limitations": {
            "synthetic": SYNTHETIC_LIMITATIONS,
            "monitoring": MONITORING_LIMITATIONS,
        },
        "false_capability_flags": FALSE_CAPABILITY_FLAGS,
        "retention": {
            "flows_days": 30,
            "feature_model_monitoring_evidence_days": 30,
            "reports_days": 30,
            "alerts_incidents_notes_audit_days": 180,
            "exceptional_holds_enabled": False,
        },
        "claims": {
            "synthetic_contract_demo": "allowed",
            "real_world_detection_performance": "prohibited",
            "real_world_prevention_effectiveness": "prohibited",
            "production_readiness": "prohibited",
            "online_inference": "prohibited",
        },
    }


def write_evidence(root: Path, output: Path) -> dict[str, object]:
    evidence = build_evidence(root)
    output = output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_name(f".{output.name}.tmp")
    temporary.write_text(json.dumps(evidence, sort_keys=True, indent=2) + "\n", encoding="utf-8")
    temporary.chmod(0o600)
    temporary.replace(output)
    output.chmod(0o600)
    return evidence


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, default=Path.cwd())
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        evidence = write_evidence(args.project_root, args.output)
    except (OSError, PortfolioEvidenceError) as exc:
        print(f"portfolio evidence blocked: {exc}")
        return 1
    print(f"portfolio evidence written: {args.output.resolve()}")
    print(f"identity_sha256: {evidence['identity_sha256']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
